using Matdance.Cli.Services;

namespace Matdance.Cli.Models;
public class ScheduledTaskItem { public string TaskId { get; set; } = string.Empty; public string Agent { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public string Status { get; set; } = ScheduledTaskStatuses.Enabled; public string RunState { get; set; } = ScheduledTaskRunStates.Idle; public string TimeZone { get; set; } = UserTimeZoneService.GetDefaultTimeZoneId(); public ScheduledTaskSchedule Schedule { get; set; } = new(); public List<ScheduledTaskTarget> Targets { get; set; } = new(); public string? CreatedFromSession { get; set; } public bool IsSystem { get; set; } public DateTimeOffset CreatedAt { get; set; } = UserTimeZoneService.Now(); public DateTimeOffset UpdatedAt { get; set; } = UserTimeZoneService.Now(); public DateTimeOffset? NextRunAt { get; set; } public DateTimeOffset? LastRunAt { get; set; } public string? LastRunStatus { get; set; } public string? LastRunSummary { get; set; } public int RunCount { get; set; } public int FailureCount { get; set; } public string? ActiveRunId { get; set; } public DateTimeOffset? ActiveRunStartedAt { get; set; } public DateTimeOffset? ActiveRunLastHeartbeatAt { get; set; } public string? ActiveRunHeartbeatKind { get; set; } public string? ActiveRunHeartbeatMessage { get; set; } public DateTimeOffset? StalledUntil { get; set; } public string? RepairedFromTaskId { get; set; } public string? RepairReason { get; set; } }
public class ScheduledTaskSchedule { public string Type { get; set; } = ScheduledTaskScheduleTypes.Once; public string? RunAt { get; set; } public string? StartAt { get; set; } public string? EndAt { get; set; } public int? IntervalMinutes { get; set; } public int? MaxRuns { get; set; } public string? Time { get; set; } public List<string>? Times { get; set; } public string? StartTime { get; set; } public string? WindowStart { get; set; } public string? WindowEnd { get; set; } public int? CountPerDay { get; set; } public string? StartDate { get; set; } public string? EndDate { get; set; } }
public class ScheduledTaskTarget { public string Type { get; set; } = ScheduledTaskTargetTypes.CreatedSession; public string? SessionId { get; set; } }
public class ScheduledTaskRun { public string RunId { get; set; } = string.Empty; public string TaskId { get; set; } = string.Empty; public string Agent { get; set; } = string.Empty; public string Trigger { get; set; } = "schedule"; public DateTimeOffset? ScheduledAt { get; set; } public string? CatchUpReason { get; set; } public DateTimeOffset StartedAt { get; set; } = UserTimeZoneService.Now(); public DateTimeOffset? FinishedAt { get; set; } public string Status { get; set; } = ScheduledTaskRunStatuses.Running; public string? Output { get; set; } public string? Error { get; set; } public string? ErrorType { get; set; } public string? Diagnostic { get; set; } public DateTimeOffset? LastHeartbeatAt { get; set; } public string? HeartbeatKind { get; set; } public string? HeartbeatMessage { get; set; } public string? ContextSnapshot { get; set; } public List<ScheduledTaskRunEvent> Events { get; set; } = new(); public List<ScheduledTaskDeliveryResult> DeliveryResults { get; set; } = new(); }
public class ScheduledTaskRunEvent { public DateTimeOffset Timestamp { get; set; } = UserTimeZoneService.Now(); public string Type { get; set; } = string.Empty; public string? Message { get; set; } public string? ToolName { get; set; } public string? ToolArguments { get; set; } public string? ToolResult { get; set; } public string? Status { get; set; } }
public class ScheduledTaskDeliveryResult { public ScheduledTaskTarget Target { get; set; } = new(); public string? SessionId { get; set; } public string Status { get; set; } = "pending"; public string? Error { get; set; } }
public class ScheduledTaskCreateRequest { public string Agent { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public string? TimeZone { get; set; } public ScheduledTaskSchedule Schedule { get; set; } = new(); public List<ScheduledTaskTarget>? Targets { get; set; } public string? CreatedFromSession { get; set; } }
public class ScheduledTaskEditRequest { public string Agent { get; set; } = string.Empty; public string TaskId { get; set; } = string.Empty; public string? Title { get; set; } public string? Content { get; set; } public string? TimeZone { get; set; } public string? Status { get; set; } public ScheduledTaskSchedule? Schedule { get; set; } public List<ScheduledTaskTarget>? Targets { get; set; } }
public class ScheduledTaskActionRequest { public string Agent { get; set; } = string.Empty; public string TaskId { get; set; } = string.Empty; public string? Reason { get; set; } }
public class ScheduledTaskPage { public List<ScheduledTaskItem> Items { get; set; } = new(); public int Page { get; set; } public int PageSize { get; set; } public int Total { get; set; } }
public static class ScheduledTaskStatuses { public const string Enabled = "enabled"; public const string Paused = "paused"; public const string Completed = "completed"; public const string Deleted = "deleted"; public const string Quarantined = "quarantined"; public const string Replaced = "replaced"; }
public static class ScheduledTaskRunStates { public const string Idle = "idle"; public const string Running = "running"; }
public static class ScheduledTaskRunStatuses { public const string Running = "running"; public const string Succeeded = "succeeded"; public const string Failed = "failed"; public const string Canceled = "canceled"; public const string Interrupted = "interrupted"; public const string Stalled = "stalled"; }
public static class ScheduledTaskScheduleTypes { public const string Once = "once"; public const string Interval = "interval"; public const string AfterCount = "after_count"; public const string Daily = "daily"; public const string DailyCount = "daily_count"; public const string DailyWindow = "daily_window"; public const string DailyTimes = "daily_times"; }
public static class ScheduledTaskTargetTypes { public const string CreatedSession = "created_session"; public const string Session = "session"; public const string AllAgentSessions = "all_agent_sessions"; public const string NotificationSession = "notification_session"; }
